version: '3'

networks:
    crgroups-client-network:

services:
    crgroups-client-nginx:
        build:
            context: ./nginx/
            target: dev
        tty: true
        environment:
            PHP_FPM_HOST: crgroups-client-php:9000
        volumes:
            - ./:/var/www/
            - ./nginx/templates:/etc/nginx/templates
        networks:
            - crgroups-client-network
        ports:
            - 8080:80
    crgroups-client-php:
        build:
            context: ./
            target: dev
        tty: true
        volumes:
            - ./:/var/www/
        networks:
            - crgroups-client-network

