apiVersion: v1
kind: Service
metadata:
    name: crgroups-client
spec:
    type: LoadBalancer
    selector:
        app: crgroups-client
    ports:
        - protocol: TCP
          name: http
          port: 8080
          targetPort: 80