name: On Master Push Actions

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: crgroups-client
  AZURE_WEBAPP_PACKAGE_PATH: .

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZ_PROD_PUB_PROFILE  }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
